[change] Added ansible role
openwisp/ansible-wireguard-openwisp pull request #1
Opened 2021-04-21 10:25 UTC by pandafy

2021-04-26 20:46 UTC, pandafy commented
I have tested the latest commit with RHEL 8 and it works well. 

In the the `Wireguard` installation docs, the [method 2 of installting on CentOS 8](https://www.wireguard.com/install/#centos-8-module-plus-module-kmod-module-dkms-tools) is similar with that of RHEL 8 and hence I implemented that. But on the instance I was testing, the current implementation does not work. Maybe it just that the VM I was testing it on was using a non-standard kernel. 

We need to test it more. We might need to add support for non-standard kernels. This should not be hard though.

2021-05-06 02:59 UTC, nemesisdesign reviewed
Great progress Gagan! Mostly minor improvements remaining, see below.

2021-05-06 02:59 UTC, nemesisdesign commented on README.md
> +via `ansible-galaxy`
semicolon missing here

2021-05-06 02:59 UTC, nemesisdesign commented on README.md
> +ansible-galaxy install git+https://github.com/openwisp/ansible-wireguard-openwisp.git
are you sure this installs it as `openwisp2.wireguard_updater`

2021-05-06 02:59 UTC, nemesisdesign commented on README.md
> +    # (a self-signed SSL cert will be generated if omitted)
is it possible to include an example which generates a certificate with letsencrypt?

2021-05-06 02:59 UTC, nemesisdesign commented on tasks/apt.yml
> +      fail:
some warnings here are complaining, are these fixable?

2021-05-06 02:59 UTC, nemesisdesign commented on tasks/flask.yml
> +    supervisord_conf_extension: ".ini"
same here

2021-05-06 02:59 UTC, nemesisdesign commented on tasks/flask.yml
> +    supervisord_conf_extension: ".conf"
same here

2021-05-06 02:59 UTC, nemesisdesign commented on tasks/main.yml
> +  fail: msg="Variable '{{ item }}' is not defined"
same here

2021-05-06 02:59 UTC, nemesisdesign commented on tasks/pip.yml
> +    virtualenv_command: "virtualenv-3"
same here

2021-05-06 02:59 UTC, nemesisdesign commented on .ansible-lint
> +  - '106' # Role name {} does not match ``^[a-z][a-z0-9_]+$`` pattern'
in this file there are several warnings that should be easily fixable

2021-05-06 02:59 UTC, nemesisdesign commented on README.md
> +Ansible role that installs WireGuard and management scripts for OpenWISP.
let's make explicit what this role does:

once installed and configured correctly with OpenWISP (we can link back the wireguard and wireguard vxlan sections of the openwisp-controller README), peers are managed automatically by OpenWISP without the need of manual intervention. 

Feel free to reword it, but make sure this is prominent and has enough emphasis. Users may end up here while looking for a different thing regarding wireguard, so once they read this they may feel compelled to find out more.

2021-05-06 19:57 UTC, pandafy commented on README.md
> +ansible-galaxy install git+https://github.com/openwisp/ansible-wireguard-openwisp.git
You are right, it will install it as openwisp-wireguard-openwisp. I asked on #ansible IRC and there isn't a way to install it using ansible-galaxy and change it's name. I have update the example-playbook to use `ansible-wireguard-openwisip` instead. 

Alternatively we could use 

```
git clone https://github.com/openwisp/ansible-wireguard-openwisp ~/.ansible/roles/openwisp2.wireguard_updater
```

But it will just confuse users. Until we publish the role, we can keep using `ansible-wireguard-openwisp` in docs.

2021-05-06 21:08 UTC, nemesisdesign requested changes
Please make sure the wireguard tunnel is brought up at boot.

2021-05-11 11:32 UTC, merged