[fix] Fixed update_vxlan script
openwisp/ansible-wireguard-openwisp pull request #4
Opened 2021-05-11 11:40 UTC by pandafy

- update_vxlan.py was not using sudo while executing nmcli commands,
fixed it.
- Updated the update_wireguard.sh script to move applied vxlan.json
  to APPLIED_CONF_DIR

2021-05-12 02:53 UTC, nemesisdesign requested changes

2021-05-12 02:53 UTC, nemesisdesign commented on templates/update_scripts/update_wireguard.sh.j2
> +        umask 0117; mv -f "$CONF_DIR/vxlan.json" "$_APPLIED_CONF_DIR/vxlan.json"
why this compression? Can you avoid the compression and add a comment on why `umask 0117;` is needed?

2021-05-12 02:53 UTC, nemesisdesign commented on templates/update_scripts/update_wireguard.sh.j2
> -    test -f "$CONF_DIR/vxlan.json" && ./update_vxlan.py "$CONF_DIR/vxlan.json"
can't we call `sudo ./update_vxlan.py` here? Have you already tried that?

2021-05-12 17:17 UTC, pandafy commented on templates/update_scripts/update_wireguard.sh.j2
> -    test -f "$CONF_DIR/vxlan.json" && ./update_vxlan.py "$CONF_DIR/vxlan.json"
`openwisp`  user has permissions to run only limited programs with escalated privileges. 

https://github.com/openwisp/ansible-wireguard-openwisp/blob/be2c20d391485794629eea60af3318dbf38436ca/files/sudoers.d/openwisp#L1

We can add permissions to the openwisp user to run update_vxlan.py with escalated priveleges. It is usually suggested to also add the checksum of the script in the sudoers file to ensure that no one can modify the script and run it with escalated privileges. This would have added complexity to the flow of execution of role, hence I went ahead with this.

2021-05-12 18:56 UTC, nemesisdesign commented on templates/update_scripts/update_wireguard.sh.j2
> -    test -f "$CONF_DIR/vxlan.json" && ./update_vxlan.py "$CONF_DIR/vxlan.json"
what if we install the script in `/usr/bin/` then we should be able to trust that no unauthorized user has changed it, otherwise we should apply the same strategy (add checksums) to the other programs allowed to be run as sudo.

The reason for this is that if we want this script to become a package, we cannot assume it can call sudo, did you think about it?

It's a minor thing BTW.

2021-05-17 19:20 UTC, nemesisdesign approved these changes
Thanks! :+1

2021-05-18 11:22 UTC, merged